import { Injectable } from '@angular/core';
import { FurnitureItem } from '../models/furniture.model';

@Injectable({
  providedIn: 'root'
})
export class FurnitureService {
  private furnitureItems: FurnitureItem[] = [
    {
      id: 'modern-fluted-tv-unit-01',
      name: 'Fluted Wood Acoustic TV Media Console',
      nameAm: 'የተሟላ የሳሎን ቲቪ ግድግዳ እና ተንሳፋፊ ካቢኔት',
      category: 'living',
      categoryLabel: 'Living & Media Wall',
      categoryLabelAm: 'ሳሎን እና የቲቪ ግድግዳ',
      dimensions: '320cm (W) x 240cm (H) x 38cm (D)',
      woodType: 'High-Density Moisture-Proof MDF with Natural Timber Slats',
      finish: 'Matte Charcoal & 3000K Warm Integrated LED Strip Channels',
      priceNote: 'Custom fabricated per client living room blueprints.',
      priceNoteAm: 'እንደ ሳሎንዎ ስፋትና ቅርጽ በልዩ ሁኔታ የሚዘጋጅ።',
      description: 'Custom contemporary media wall featuring vertical acoustic sound-dampening timber slats, concealed wiring channels, cantilevered floating storage drawers with soft-close runners, and ambient perimeter LED backlighting.',
      descriptionAm: 'ለዘመናዊ ሳሎን የሚሆን ውብ የቲቪ ግድግዳ፤ ድምጽ የሚቀንሱ የእንጨት ዲዛይኖች፣ የተሰወሩ የሽቦ መስመሮች፣ ተንሳፋፊ መሳቢያዎች እና የውስጥ የኤልኢዲ መብራቶች ያሉት።',
      image: '/images/furniture/furn-01.jpg',
      featured: true,
      leadTime: '10 - 15 business days'
    },
    {
      id: 'luxury-wpc-tv-wall-02',
      name: 'Modern Marble & WPC Slotted Wall Entertainment Center',
      nameAm: 'የእብነበረድ እና የደብሊውፒሲ ሳሎን ጌጥ',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን',
      dimensions: '300cm (W) x 260cm (H) x 40cm (D)',
      woodType: 'Waterproof WPC Louvres & UV High-Gloss Faux Marble Slab',
      finish: 'High-Gloss Polished Marble Finish with Gold Accent Profiles',
      priceNote: 'Tailored dimensions for residential villas and luxury apartments.',
      priceNoteAm: 'ለውብ ቪላዎች እና አፓርትመንቶች የሚሆን።',
      description: 'Grand entertainment unit combining UV high-gloss marble sheet backing with fluted acoustic WPC side panels, illuminated floating display shelves, and integrated soundbar recess.',
      descriptionAm: 'የእብነበረድ እይታ ያለው ግድግዳ ከደብሊውፒሲ የእንጨት ቅርጾችና ከመብራት መደርደሪያዎች ጋር የተዋሃደ።',
      image: '/images/furniture/furn-02.jpg',
      featured: true,
      leadTime: '10 - 14 business days'
    },
    {
      id: 'minimalist-tv-console-03',
      name: 'Nordic Minimalist Floating TV Console & Display',
      nameAm: 'ኖርዲክ ተንሳፋፊ የቲቪ ካቢኔት እና መደርደሪያ',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን',
      dimensions: '260cm (W) x 220cm (H) x 35cm (D)',
      woodType: 'Solid Natural Oak Veneer & Reinforced Steel Brackets',
      finish: 'Satin Clear Protective Topcoat & Flush Handleless Drawers',
      priceNote: 'Includes full wall mounting and cable routing installation.',
      priceNoteAm: 'የግድግዳ ላይ ገጠማ እና የሽቦ መደበቂያን ያካትታል።',
      description: 'Clean Scandinavian-inspired floating media center with push-to-open flush drawers, tempered glass display cubbies, and warm indirect under-cabinet floor wash lighting.',
      descriptionAm: 'ቀለል ያለ እና ዘመናዊ ተንሳፋፊ የቲቪ ካቢኔት፤ ያለ እጀታ የሚከፈቱ መሳቢያዎች እና የብርሃን ድምቀት ያለው።',
      image: '/images/furniture/furn-03.jpg',
      featured: false,
      leadTime: '8 - 12 business days'
    },
    {
      id: 'dual-tone-tv-unit-04',
      name: 'Dual-Tone Architectural TV Feature Wall',
      nameAm: 'ባለ ሁለት ቀለም ዘመናዊ የቲቪ ግድግዳ',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን',
      dimensions: '340cm (W) x 270cm (H) x 42cm (D)',
      woodType: 'Premium Textured Melamine & Matt Lacquered Fascia',
      finish: 'Super Matt Anti-Scratch Finish & Soft-Close Blum Hinges',
      priceNote: 'Custom sized to accommodate 65"-85" television displays.',
      priceNoteAm: 'ከ65 እስከ 85 ኢንች ቴሌቪዥን ለሚጠቀሙ የሚመጥን።',
      description: 'Commanding floor-to-ceiling media installation featuring dark walnut slat arrays contrasted with warm cream storage niches and smart remote-controlled illumination.',
      descriptionAm: 'ከወለል እስከ ጣሪያ የሚደርስ ውብ የቲቪ ግድግዳ ካቢኔት፤ የተሟላ የቁሳቁስ ማስቀመጫ ያለው።',
      image: '/images/furniture/furn-04.jpg',
      featured: true,
      leadTime: '12 - 16 business days'
    },
    {
      id: 'artisan-island-kitchen-05',
      name: 'Artisan Modern Modular Kitchen with Island Bar',
      nameAm: 'ዘመናዊ የወጥ ቤት ካቢኔት እና የአይላንድ ባር',
      category: 'custom',
      categoryLabel: 'Kitchen Cabinetry',
      categoryLabelAm: 'ወጥ ቤት እና ካቢኔቶች',
      dimensions: 'Custom tailored to architectural floorplan',
      woodType: 'Moisture-Resistant Marine-Grade HDF & Solid Quartz Countertops',
      finish: 'Super Matte Polyurethane & Integrated J-Pull Profiles',
      priceNote: 'Priced per linear meter based on chosen quartz stone and fittings.',
      priceNoteAm: 'እንደ ርዝመቱ መጠን እና እንደ ተመረጠው እብነበረድ ዋጋ ይሰላል።',
      description: 'Premium modular kitchen installation featuring seamless quartz island worktop, bi-fold lift-up upper cabinets, Blum soft-close tandem drawers, and integrated LED task lighting.',
      descriptionAm: 'የውሃና እርጥበት መከላከያ ያለው የወጥ ቤት ካቢኔት፤ ኳርትዝ እብነበረድ፣ ዘመናዊ መሳቢያዎች እና የጀርመን እቃዎች ያሉት።',
      image: '/images/furniture/furn-08.jpg',
      featured: true,
      leadTime: '20 - 28 business days'
    },
    {
      id: 'luxury-quartz-kitchen-06',
      name: 'L-Shaped Luxury Quartz & High-Gloss Kitchen',
      nameAm: 'ባለ ኤል ቅርጽ የቅንጦት የወጥ ቤት ካቢኔት',
      category: 'custom',
      categoryLabel: 'Kitchen Cabinetry',
      categoryLabelAm: 'ወጥ ቤት እና ካቢኔቶች',
      dimensions: 'Custom modular fit per blueprint measurements',
      woodType: 'High-Density Gloss Acrylic Board & Calacatta Quartz Counter',
      finish: 'Mirror High-Gloss Reflection & Stainless Steel Kickplates',
      priceNote: 'Includes spice pullouts, trash organizers, and undermount sink cut.',
      priceNoteAm: 'የቅመማ ቅመም መሳቢያዎችና የእቃ ማጠቢያ ቦታን ያጠቃልላል።',
      description: 'Contemporary L-shaped kitchen layout with Calacatta quartz waterfall edge, concealed integrated pantry larders, and heavy-duty corner carousel storage units.',
      descriptionAm: 'የሚያምር የኤል ቅርጽ ወጥ ቤት ካቢኔት፤ ከፍተኛ የዕቃ መያዝ አቅምና ጥራት ያለው ኳርትዝ እብነበረድ ያለው።',
      image: '/images/furniture/furn-09.jpg',
      featured: false,
      leadTime: '18 - 25 business days'
    },
    {
      id: 'matte-black-kitchen-07',
      name: 'Matte Charcoal & Warm Oak Executive Kitchen',
      nameAm: 'ዘመናዊ ጥቁርና የእንጨት ውህድ የወጥ ቤት ካቢኔት',
      category: 'custom',
      categoryLabel: 'Kitchen Cabinetry',
      categoryLabelAm: 'ወጥ ቤት እና ካቢኔቶች',
      dimensions: 'Custom modular sizing per residential layout',
      woodType: 'Hydrophobic HDF with Natural Oak Open Shelving Insets',
      finish: 'Velvet Soft-Touch Anti-Fingerprint Surface Coating',
      priceNote: 'Engineered with German hardware and stainless steel cutlery trays.',
      priceNoteAm: 'በከፍተኛ ጥራትና በዘመናዊ ቴክኖሎጂ የሚዘጋጅ።',
      description: 'Sophisticated dark matte kitchen concept paired with natural oak accent nooks, integrated appliance towers, and automated under-counter task lighting.',
      descriptionAm: 'ውብ ጥቁር እና የተፈጥሮ እንጨት ቀለም ያለው የወጥ ቤት ዲዛይን፤ ዘመናዊ መሳቢያዎች ያሉት።',
      image: '/images/furniture/furn-10.jpg',
      featured: true,
      leadTime: '20 - 30 business days'
    },
    {
      id: 'elysian-king-bedroom-08',
      name: 'Elysian Upholstered King Bed & Fluted Wood Headboard',
      nameAm: 'ኤሊሲያን የቅንጦት ባለከፍተኛ መኝታ አልጋ',
      category: 'bedroom',
      categoryLabel: 'Bedroom Suite',
      categoryLabelAm: 'መኝታ ቤት',
      dimensions: '200cm x 200cm Bed + 340cm Wide Accent Headboard',
      woodType: 'Solid Walnut Frame & High-Density Luxury Velvet Fabric',
      finish: 'Natural Satin Wood Sealant & Indirect 2700K Headboard Glow',
      priceNote: 'Includes bedframe, floor-to-ceiling headboard, and two nightstands.',
      priceNoteAm: 'አልጋውን፣ የግድግዳ ጌጡን እና ሁለት ተንሳፋፊ ኮሞዲኖዎችን ያካትታል።',
      description: 'Architectural king bedroom suite featuring an expansive floor-to-ceiling upholstered accent wall with vertical fluted timber dividers and cantilevered dual nightstands.',
      descriptionAm: 'የተሟላ የቅንጦት ኪንግ ሳይዝ አልጋ፤ ከጣሪያ እስከ ወለል የሚደርስ የእንጨትና የጨርቅ ጌጥ፣ ተንሳፋፊ ኮሞዲኖዎች እና ጠንካራ የእንጨት አሰራር።',
      image: '/images/furniture/furn-13.jpg',
      featured: true,
      leadTime: '14 - 20 business days'
    },
    {
      id: 'master-suite-bed-09',
      name: 'Master Suite Platform Bed with Floating Bedside Tables',
      nameAm: 'ዘመናዊ ፕላትፎርም የመኝታ አልጋ እና ኮሞዲኖ',
      category: 'bedroom',
      categoryLabel: 'Bedroom Suite',
      categoryLabelAm: 'መኝታ ቤት',
      dimensions: '180cm x 200cm Mattress Platform + 280cm Headboard',
      woodType: 'Solid Teak Hardwood & Brushed Brass Detailing',
      finish: 'Matte Natural Wood Stain & Built-in USB Charging Sockets',
      priceNote: 'Custom configured in King or Queen mattress dimensions.',
      priceNoteAm: 'በኪንግ ወይም በኩዊን ሳይዝ የሚዘጋጅ።',
      description: 'Low-profile luxury platform bedframe with integrated floating nightstands, ergonomic curved headboard cushion, and concealed under-bed ambient glow.',
      descriptionAm: 'ምቹ እና ጠንካራ የመኝታ አልጋ፤ የተቀናጁ ተንሳፋፊ ኮሞዲኖዎችና የኤልኢዲ መብራት ያለው።',
      image: '/images/furniture/furn-14.jpg',
      featured: false,
      leadTime: '12 - 18 business days'
    },
    {
      id: 'smoked-glass-wardrobe-10',
      name: 'Floor-to-Ceiling Smoked Glass Sliding Wardrobe',
      nameAm: 'ዘመናዊ የጭስ መስታወት ተንሸራታች የልብስ ቁምሳጥን',
      category: 'bedroom',
      categoryLabel: 'Wardrobe Systems',
      categoryLabelAm: 'የልብስ ቁምሳጥን',
      dimensions: '300cm (W) x 270cm (H) x 65cm (D)',
      woodType: 'High-Density Melamine Core & Smoked Aluminum Framed Glass',
      finish: 'Anti-Fingerprint Finish & Motion-Sensor Internal LED Lighting',
      priceNote: 'Custom partitioned with shoe organizers, hanger rods, and drawers.',
      priceNoteAm: 'እንደ ፍላጎትዎ መሳቢያዎችና መደርደሪያዎች ተሟልተው የሚሰሩ።',
      description: 'Luxury floor-to-ceiling wardrobe system with tinted tempered glass doors, automated interior motion-sensor lights, and velvet-lined jewelry drawers.',
      descriptionAm: 'ዘመናዊ የጭስ መስታወት ተንሸራታች በር ያለው የልብስ ቁምሳጥን ከውስጥ ሴንሰር መብራቶችና መሳቢያዎች ጋር።',
      image: '/images/furniture/furn-18.jpg',
      featured: true,
      leadTime: '15 - 22 business days'
    },
    {
      id: 'walk-in-closet-wardrobe-11',
      name: 'Bespoke Walk-In Dressing Room & Wardrobe Unit',
      nameAm: 'የተሟላ የልብስ መቀየሪያ ክፍል ካቢኔቶች (Walk-In Closet)',
      category: 'bedroom',
      categoryLabel: 'Wardrobe Systems',
      categoryLabelAm: 'የልብስ ቁምሳጥን',
      dimensions: 'Custom configured for dedicated dressing rooms',
      woodType: 'Moisture-Resistant HDF with Solid Oak Edgebanding',
      finish: 'Matt Warm Gray Texture & Integrated Vertical LED Strips',
      priceNote: 'Custom manufactured to fit room alcoves and architectural recesses.',
      priceNoteAm: 'እንደ ክፍልዎ ስፋትና ቅርጽ በልዩ ሁኔታ የሚሰራ።',
      description: 'Open-concept walk-in closet system equipped with illuminated shoe display shelves, central island vanity drawer, and dedicated full-length hanging zones.',
      descriptionAm: 'ለልብስ ክፍል የሚሆን ሰፊና ዘመናዊ ካቢኔት፤ የጫማ መደርደሪያዎችና መሳቢያዎች ያሉት።',
      image: '/images/furniture/furn-19.jpg',
      featured: false,
      leadTime: '18 - 25 business days'
    },
    {
      id: 'solid-wood-dining-set-12',
      name: 'Solid Natural Hardwood Dining Table & 8-Seater Set',
      nameAm: 'ከተፈጥሮ ጠንካራ እንጨት የተሰራ የመመገቢያ ጠረጴዛና ወንበሮች',
      category: 'dining',
      categoryLabel: 'Dining Room',
      categoryLabelAm: 'የመመገቢያ ክፍል',
      dimensions: '240cm (L) x 105cm (W) x 76cm (H)',
      woodType: 'Kiln-Dried Solid Hardwood with Organic Wood Grains',
      finish: 'Matte Heat & Stain Resistant Protective Polyurethane Coat',
      priceNote: 'Includes solid dining table and 8 matching ergonomic chairs.',
      priceNoteAm: 'ጠረጴዛውን እና 8 ተስማሚ ወንበሮችን ያጠቃልላል።',
      description: 'Handcrafted solid hardwood dining centerpiece featuring continuous natural grain patterns, beveled edge profiles, and matching upholstered dining chairs.',
      descriptionAm: 'ከተፈጥሮ ጠንካራ እንጨት የተሰራ የመመገቢያ ጠረጴዛ ከውብ 8 ወንበሮች ጋር።',
      image: '/images/furniture/furn-23.jpg',
      featured: true,
      leadTime: '14 - 21 business days'
    },
    {
      id: 'executive-curved-desk-13',
      name: 'Bespoke Executive Curved Reception & Office Workstation',
      nameAm: 'ዘመናዊ የሪሴፕሽን እና የቢሮ ጠረጴዛ',
      category: 'office',
      categoryLabel: 'Executive Office & Reception',
      categoryLabelAm: 'ቢሮ እና ሪሴፕሽን',
      dimensions: '280cm (L) x 110cm (W) x 115cm (H)',
      woodType: 'Solid Hardwood Core with CNC Curved Fascia Panels',
      finish: 'High-Gloss Lacquered Exterior with Undermount LED Illumination',
      priceNote: 'Custom fabricated for corporate lobbies, hotels, and executive suites.',
      priceNoteAm: 'ለቢሮዎች፣ ሆቴሎች እና ለንግድ ተቋማት የሚዘጋጅ።',
      description: 'Commanding executive reception workstation with built-in led illumination, wire grommets, internal lockable file drawers, and polished transaction tops.',
      descriptionAm: 'ለሆቴል፣ ስፓና ለኮርፖሬት ቢሮዎች የሚሆን ውብ የሪሴፕሽን ጠረጴዛ ከኤልኢዲ መብራት ጋር።',
      image: '/images/furniture/furn-27.jpg',
      featured: true,
      leadTime: '12 - 18 business days'
    },
    {
      id: 'executive-boardroom-table-14',
      name: 'Architectural Boardroom Conference Table (12-Seater)',
      nameAm: 'የስብሰባ አዳራሽ ጠረጴዛ (ለ12 ሰዎች)',
      category: 'office',
      categoryLabel: 'Executive Office',
      categoryLabelAm: 'የቢሮ ዕቃዎች',
      dimensions: '380cm (L) x 130cm (W) x 76cm (H)',
      woodType: 'Engineered Walnut Veneer with Reinforced Steel Substructure',
      finish: 'Commercial Anti-Scratch Satin Finish with Pop-Up Power Boxes',
      priceNote: 'Includes integrated cable trays, HDMI/Power popup units.',
      priceNoteAm: 'የኤሌክትሪክና የኢንተርኔት ሽቦ ማለፊያዎች የተገጠሙለት።',
      description: 'Grand boardroom table engineered for high-level meetings, equipped with concealed flip-up power and network modules, cable management troughs, and leather-inlaid writing zones.',
      descriptionAm: 'ለድርጅቶችና ለስብሰባ አዳራሾች የሚሆን ጠንካራ እና ውብ የስብሰባ ጠረጴዛ።',
      image: '/images/furniture/furn-28.jpg',
      featured: false,
      leadTime: '15 - 22 business days'
    },
    {
      id: 'laser-cut-ceiling-panel-15',
      name: 'CNC Laser-Cut Geometric Arabesque Ceiling Panel',
      nameAm: 'በሲኤንሲ ሌዘር የተቆረጠ የጣሪያ ጌጥ ከመብራት ጋር',
      category: 'custom',
      categoryLabel: 'Architectural Woodcraft',
      categoryLabelAm: 'የእንጨት እና የጣሪያ ጥበብ',
      dimensions: 'Configured per ceiling cove span',
      woodType: 'Multi-layer Architectural Wood Composite',
      finish: 'Backlit Warm Ambient LED Diffuser Panel',
      priceNote: 'Fabricated per ceiling square meter specifications.',
      priceNoteAm: 'እንደ ጣሪያው ስፋት መጠን በልዩ ሁኔታ የሚሰራ።',
      description: 'Precision CNC-routed geometric architectural ceiling insets that provide dazzling indirect ambient illumination for luxury living and reception halls.',
      descriptionAm: 'በከፍተኛ የሌዘር ቴክኖሎጂ የተቀረጸ የጣሪያ ጌጥ፤ ለሳሎን እና ለቪላዎች ልዩ ውበት የሚሰጥ።',
      image: '/images/furniture/furn-31.jpg',
      featured: true,
      leadTime: '10 - 15 business days'
    }
  ];

  getFurnitureItems(): FurnitureItem[] {
    return this.furnitureItems;
  }

  getFeaturedFurniture(): FurnitureItem[] {
    return this.furnitureItems.filter(f => f.featured);
  }

  getFurnitureById(id: string): FurnitureItem | undefined {
    return this.furnitureItems.find(p => p.id === id);
  }

  getFurnitureByCategory(category: string): FurnitureItem[] {
    if (category === 'all') return this.furnitureItems;
    return this.furnitureItems.filter(f => f.category === category);
  }
}
