import { Injectable } from '@angular/core';
import { FurnitureItem } from '../models/furniture.model';

@Injectable({
  providedIn: 'root'
})
export class FurnitureService {
  private furnitureItems: FurnitureItem[] = [
    {
      id: 'zenith-tv-wall-unit',
      name: 'Zenith Fluted Wall TV Media Console',
      nameAm: 'ዜኒዝ ዘመናዊ የቲቪ ግድግዳ ካቢኔት',
      category: 'living',
      categoryLabel: 'Living & Media Wall',
      categoryLabelAm: 'የሳሎን ቲቪ ግድግዳ',
      dimensions: '320cm (W) x 240cm (H) x 40cm (D)',
      woodType: 'Natural Teak & High-Density MDF with Charcoal Slat Finish',
      finish: 'Matte Polyurethane & Integrated Warm 3000K LED Strip',
      priceNote: 'Custom fabricated per room spatial blueprints.',
      priceNoteAm: 'እንደ ክፍሉ ስፋትና መጠን በልዩ ሁኔታ የሚሰራ።',
      description: 'Architectural living room media wall featuring vertical acoustic timber slats, concealed cable management channels, integrated floating drawers with Blum soft-close runners, and ambient backlit shelving.',
      descriptionAm: 'ለሳሎን የሚሆን ውብ የቲቪ ግድግዳ፤ ድምጽ የሚቀንሱ የእንጨት ዲዛይኖች፣ የተሰወሩ የሽቦ መስመሮች፣ ተንሳፋፊ መሳቢያዎች እና የውስጥ የኤልኢዲ መብራቶች ያሉት።',
      image: '/images/furniture/furniture-01.jpg',
      featured: true,
      leadTime: '10 - 15 business days'
    },
    {
      id: 'floating-living-credenza',
      name: 'Contemporary Low-Profile Floating Credenza',
      nameAm: 'ተንሳፋፊ ዘመናዊ የሳሎን ካቢኔት',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን',
      dimensions: '260cm (W) x 50cm (H) x 42cm (D)',
      woodType: 'Engineered Walnut & Fluted Charcoal Panels',
      finish: 'Silk-Matte Scratch-Resistant Lacquer',
      priceNote: 'Available in dual-tone or single natural finish.',
      priceNoteAm: 'በሁለት ቀለም ወይም በአንድ የተፈጥሮ እንጨት ቀለም የሚዘጋጅ።',
      description: 'Low-profile cantilevered console featuring touch-latch handleless doors, wire access cutouts, and reinforced steel internal bracket support.',
      descriptionAm: 'ዘመናዊ እጀታ አልባ መክፈቻ ያለው ተንሳፋፊ ካቢኔት፤ ጠንካራ የውስጥ ድጋፍ እና ለሽቦዎች የተዘጋጁ ክፍተቶች ያሉት።',
      image: '/images/furniture/furniture-02.jpg',
      featured: false,
      leadTime: '8 - 12 business days'
    },
    {
      id: 'acoustic-slat-tv-wall',
      name: 'Acoustic Louvre Wall Panel & Entertainment Hub',
      nameAm: 'አኮስቲክ የእንጨት ግድግዳ እና የቲቪ ጌጥ',
      category: 'living',
      categoryLabel: 'Living & Acoustic Wall',
      categoryLabelAm: 'የሳሎን ግድግዳ ስራ',
      dimensions: '280cm (W) x 260cm (H) x 38cm (D)',
      woodType: 'Waterproof WPC & Solid Oak Insets',
      finish: 'Warm Woodgrain Texture & Magnetic Track Accents',
      priceNote: 'Includes full wall cladding and integrated storage drawers.',
      priceNoteAm: 'ሙሉ የግድግዳ ስራውንና ተንሳፋፊ መሳቢያዎችን ያካትታል።',
      description: 'Moisture-resistant WPC slat feature wall with built-in led illumination, floating console base, and flush electric socket mounts.',
      descriptionAm: 'እርጥበት የሚቋቋም የደብሊውፒሲ የእንጨት ግድግዳ ከኤልኢዲ መብራት እና የኤሌክትሪክ ሶኬቶች መግጠሚያ ጋር።',
      image: '/images/furniture/furniture-03.jpg',
      featured: true,
      leadTime: '10 - 14 business days'
    },
    {
      id: 'modern-media-console-drawers',
      name: 'Minimalist Media Console with Soft-Close Drawers',
      nameAm: 'ሚኒማሊስት የቲቪ ማስቀመጫ ከስላሳ መሳቢያዎች ጋር',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን',
      dimensions: '240cm (W) x 55cm (H) x 45cm (D)',
      woodType: 'Solid Natural Oak with Matte White Accents',
      finish: 'Natural Matte Polyurethane Protective Coat',
      priceNote: 'Made to order with custom drawer dividers.',
      priceNoteAm: 'በውስጡ የተከፋፈሉ መደርደሪያዎች ያሉት።',
      description: 'Clean Scandinavian lines with solid oak perimeter frame, bevelled top edge, and premium soft-closing drawer guides.',
      descriptionAm: 'የተረጋጋ የሰሜናዊ አውሮፓ ዲዛይን፤ የተፈጥሮ የኦክ እንጨትና ጥራት ያላቸው መሳቢያዎች።',
      image: '/images/furniture/furniture-04.jpg',
      featured: false,
      leadTime: '7 - 10 business days'
    },
    {
      id: 'luxury-accent-lounge-set',
      name: 'Artisan Curved Lounge Sofa & Sculpted Coffee Table',
      nameAm: 'ዘመናዊ ቅርፅ ያለው ሶፋ እና የቡና ጠረጴዛ',
      category: 'living',
      categoryLabel: 'Living & Lounge',
      categoryLabelAm: 'ሶፋና የሳሎን መቀመጫ',
      dimensions: 'Sofa: 290cm x 105cm / Table: 120cm x 75cm',
      woodType: 'Solid Ash Wood Frame & High-Resilience Upholstery',
      finish: 'Stain-Resistant Textured Bouclé & Polished Wood',
      priceNote: 'Fabric color and texture customizable upon request.',
      priceNoteAm: 'የጨርቁ ቀለምና ዓይነት እንደ ምርጫዎ ይቀየራል።',
      description: 'Curvaceous organic sofa suite paired with custom solid timber coffee table, offering unmatched comfort and contemporary aesthetic.',
      descriptionAm: 'ለሳሎን ልዩ ግርማ የሚሰጥ ዘመናዊ ቅርጽ ያለው ሶፋ ከጠንካራ የተፈጥሮ እንጨት የቡና ጠረጴዛ ጋር።',
      image: '/images/furniture/furniture-05.jpg',
      featured: true,
      leadTime: '14 - 18 business days'
    },
    {
      id: 'living-room-display-bookcase',
      name: 'Architectural Open Display Shelf & Bookcase',
      nameAm: 'ዘመናዊ ክፍት የመጽሐፍ እና የጌጥ መደርደሪያ',
      category: 'living',
      categoryLabel: 'Living Room',
      categoryLabelAm: 'ሳሎን እና መደርደሪያ',
      dimensions: '200cm (W) x 240cm (H) x 35cm (D)',
      woodType: 'Natural Teak Veneer & Darkened Steel Profiles',
      finish: 'Natural Oil Wood Polish & Matte Black Metal',
      priceNote: 'Configurable shelf heights and LED strip placement.',
      priceNoteAm: 'የመደርደሪያዎቹ ከፍታ እንደ ፍላጎትዎ የሚስተካከል።',
      description: 'Statement floor-to-ceiling display shelving with asymmetric compartments, warm accent lights, and concealed lower storage compartments.',
      descriptionAm: 'ለጌጦች፣ ለመጻሕፍትና ለዋንጫዎች የሚሆን ውብ መደርደሪያ ከታች ከተሰወረ ካቢኔት ጋር።',
      image: '/images/furniture/furniture-06.jpg',
      featured: false,
      leadTime: '10 - 15 business days'
    },
    {
      id: 'elysian-king-bedframe',
      name: 'Elysian King Bedframe & Fluted Accent Headboard',
      nameAm: 'ኤሊሲያን የቅንጦት ባለከፍተኛ መኝታ አልጋ',
      category: 'bedroom',
      categoryLabel: 'Bedroom Suite',
      categoryLabelAm: 'መኝታ ቤት',
      dimensions: '200cm x 200cm Bed + 340cm Wide Accent Headboard',
      woodType: 'Solid Walnut Frame & Premium Foam Upholstery',
      finish: 'Natural Satin Lacquer & Warm Bedside Backlighting',
      priceNote: 'Includes frame, wall headboard panel, and dual floating nightstands.',
      priceNoteAm: 'አልጋውን፣ የግድግዳ ጌጡን እና ሁለት ተንሳፋፊ ኮሞዲኖዎችን ያካትታል።',
      description: 'Opulent king-size bed suite featuring an expansive floor-to-ceiling upholstered and timber fluted headboard, cantilevered bedside floating tables, and solid internal framing.',
      descriptionAm: 'የተሟላ የቅንጦት ኪንግ ሳይዝ አልጋ፤ ከጣሪያ እስከ ወለል የሚደርስ የእንጨትና የጨርቅ ጌጥ፣ ተንሳፋፊ ኮሞዲኖዎች እና ጠንካራ የእንጨት አሰራር።',
      image: '/images/furniture/furniture-07.jpg',
      featured: true,
      leadTime: '14 - 20 business days'
    },
    {
      id: 'tinted-glass-sliding-wardrobe',
      name: 'Floor-to-Ceiling Tinted Glass Sliding Wardrobe',
      nameAm: 'ዘመናዊ የመስታወት ተንሸራታች የልብስ ቁምሳጥን',
      category: 'bedroom',
      categoryLabel: 'Wardrobe Systems',
      categoryLabelAm: 'የልብስ ቁምሳጥን',
      dimensions: '300cm (W) x 270cm (H) x 65cm (D)',
      woodType: 'High-Density Moisture-Resistant Melamine & Aluminum Frames',
      finish: 'Smoked Grey Glass & Automated Sensor LED Channels',
      priceNote: 'Custom configured with velvet accessory drawers and trouser racks.',
      priceNoteAm: 'እንደ ፍላጎትዎ መሳቢያዎችና የልብስ መስቀያዎች ያሉት።',
      description: 'Architectural wardrobe with smoked tempered glass doors, automated interior sensor lights, velvet-lined jewelry drawers, and heavy-duty smooth sliding track mechanisms.',
      descriptionAm: 'ዘመናዊ የጭስ መስታወት ተንሸራታች በር ያለው የልብስ ቁምሳጥን ከውስጥ ሴንሰር መብራቶችና መሳቢያዎች ጋር።',
      image: '/images/furniture/furniture-08.jpg',
      featured: true,
      leadTime: '15 - 22 business days'
    },
    {
      id: 'minimalist-nordic-bed',
      name: 'Nordic Low-Profile Upholstered Bed with LED',
      nameAm: 'ኖርዲክ ዘመናዊ የመኝታ አልጋ',
      category: 'bedroom',
      categoryLabel: 'Bedroom Suite',
      categoryLabelAm: 'መኝታ ቤት',
      dimensions: '180cm x 200cm (Queen / King)',
      woodType: 'Solid Beech & Premium Linen Fabric',
      finish: 'Matte Natural Wood Finish & Soft Edge Profile',
      priceNote: 'Includes reinforced orthopedic slat base.',
      priceNoteAm: 'የሰውነት ክብደት የሚሸከም ጠንካራ የእንጨት መሰረት ያለው።',
      description: 'Contemporary low-profile bed designed for modern bedrooms, offering ergonomic padded backrest and under-bed ambient nightlight glow.',
      descriptionAm: 'ለዘመናዊ መኝታ ክፍል የሚሆን ምቹ ኖርዲክ አልጋ ከለስላሳ የጀርባ ደጋፊ ጋር።',
      image: '/images/furniture/furniture-09.jpg',
      featured: false,
      leadTime: '10 - 14 business days'
    },
    {
      id: 'bespoke-vanity-dressing-table',
      name: 'Bespoke Dressing Vanity with Illuminated Mirror',
      nameAm: 'የመኝታ ክፍል ኮሞዲኖ እና የሚያበራ መስታወት',
      category: 'bedroom',
      categoryLabel: 'Bedroom Vanity',
      categoryLabelAm: 'የመዋቢያ ጠረጴዛ',
      dimensions: '140cm (W) x 180cm (H) x 45cm (D)',
      woodType: 'High-Gloss Lacquered MDF & Solid Brass Accents',
      finish: 'Scratch-Proof Satin & Touch-Dimmer LED Mirror',
      priceNote: 'Includes upholstered vanity stool with storage.',
      priceNoteAm: 'የመዋቢያ መቀመጫ ወንበርን ያካትታል።',
      description: 'Elegant vanity console with soft-close velvet lined organizer compartments, frosted ambient LED ring mirror, and matching compact ottoman.',
      descriptionAm: 'ለመዋቢያ እቃዎች መደርደሪያ መሳቢያዎች ያሉት ውብ የሴቶች ኮሞዲኖ ከንክኪ መብራት መስታወት ጋር።',
      image: '/images/furniture/furniture-10.jpg',
      featured: false,
      leadTime: '10 - 14 business days'
    },
    {
      id: 'walkin-closet-organizer',
      name: 'Master Walk-In Closet Island & Storage Suite',
      nameAm: 'የተሟላ የልብስ ክፍል እና የመሃል ደሴት ካቢኔት',
      category: 'bedroom',
      categoryLabel: 'Wardrobe Systems',
      categoryLabelAm: 'የልብስ ክፍል',
      dimensions: 'Custom tailored to dedicated dressing rooms',
      woodType: 'Moisture-Proof Engineered Core & Solid Wood Trim',
      finish: 'Charcoal Matte with Integrated Perimeter LEDs',
      priceNote: 'Priced based on linear layout and interior accessories.',
      priceNoteAm: 'እንደ ክፍሉ መጠን እና እንደ ተመረጡት መሳቢያዎች ዋጋ ይሰላል።',
      description: 'Luxury walk-in closet solution with glass-front display modules, watch and jewelry showcase island, and dedicated shoe illumination shelves.',
      descriptionAm: 'ለልብስ፣ ለጫማ፣ ለሰዓትና ለጌጣጌጥ የሚሆኑ የተሟሉ ዘመናዊ መደርደሪያዎችና መሳቢያዎች።',
      image: '/images/furniture/furniture-11.jpg',
      featured: true,
      leadTime: '18 - 25 business days'
    },
    {
      id: 'dual-floating-nightstands',
      name: 'Cantilevered Bedside Floating Nightstands (Pair)',
      nameAm: 'ተንሳፋፊ የመኝታ ክፍል ኮሞዲኖዎች (ጥንድ)',
      category: 'bedroom',
      categoryLabel: 'Bedroom Suite',
      categoryLabelAm: 'መኝታ ቤት',
      dimensions: '55cm (W) x 30cm (H) x 38cm (D) each',
      woodType: 'Solid Oak with Fluted Front Faces',
      finish: 'Matte Protective Seal & Integrated USB Wireless Cutout',
      priceNote: 'Sold as a pair with wall-mount anchor hardware.',
      priceNoteAm: 'በጥንድ ከግድግዳ መግጠሚያ ጋር የሚቀርብ።',
      description: 'Pair of sleek wall-mounted nightstands with push-to-open smooth drawers and built-in hidden cable passages for night lamps and chargers.',
      descriptionAm: 'ከግድግዳ ላይ የሚገጠሙ ሁለት ውብ ኮሞዲኖዎች ከስልክ ቻርጀር ማሳለፊያ ጋር።',
      image: '/images/furniture/furniture-12.jpg',
      featured: false,
      leadTime: '6 - 9 business days'
    },
    {
      id: 'modern-island-kitchen-system',
      name: 'Artisan Modern Kitchen Cabinetry & Island System',
      nameAm: 'ዘመናዊ የወጥ ቤት ካቢኔት እና የመሃል ደሴት',
      category: 'custom',
      categoryLabel: 'Kitchen & Cabinetry',
      categoryLabelAm: 'ወጥ ቤት እና ካቢኔቶች',
      dimensions: 'Custom modular fit to architectural blueprints',
      woodType: 'Moisture Resistant HDF & Quartz Solid Surface',
      finish: 'Super Matte Anti-Scratch Finish with Gola Aluminum Profiles',
      priceNote: 'Priced per linear meter based on stone and hardware selection.',
      priceNoteAm: 'እንደ ርዝመቱ መጠን እና እንደ ተመረጠው እብነበረድ ዋጋ ይሰላል።',
      description: 'Engineered modular kitchen with quartz stone counters, lift-up upper cabinet doors, pull-out spice larders, and soft-closing German hinges.',
      descriptionAm: 'የውሃና እርጥበት መከላከያ ያላቸው ጥራት ያላቸው የወጥ ቤት ካቢኔቶች፤ ኳርትዝ እብነበረድ፣ ዘመናዊ መሳቢያዎች እና የሚያማምሩ ቀለሞች።',
      image: '/images/furniture/furniture-13.jpg',
      featured: true,
      leadTime: '20 - 30 business days'
    },
    {
      id: 'pantry-tall-cabinet-suite',
      name: 'Floor-to-Ceiling Pantry & Integrated Appliance Suite',
      nameAm: 'የተሟላ የዕቃ ማስቀመጫ የወጥ ቤት ቁምሳጥን',
      category: 'custom',
      categoryLabel: 'Kitchen & Cabinetry',
      categoryLabelAm: 'ወጥ ቤት እና ካቢኔቶች',
      dimensions: '220cm (W) x 260cm (H) x 60cm (D)',
      woodType: 'High-Density Moisture-Proof Marine Core',
      finish: 'Velvet Matte Navy & Brushed Brass Hardware',
      priceNote: 'Custom cutouts for built-in ovens, microwaves, and refrigerators.',
      priceNoteAm: 'ለኦቨን፣ ማይክሮዌቭ እና ማቀዝቀዣ መግጠሚያ ቦታ ያለው።',
      description: 'High-capacity vertical kitchen storage featuring heavy-duty tandem pullout pantries, appliance garages, and seamless built-in oven enclosures.',
      descriptionAm: 'ብዙ እቃዎችን የሚይዝ ዘመናዊ የወጥ ቤት ቁምሳጥን ከኦቨንና ማቀዝቀዣ ማስገቢያ ጋር።',
      image: '/images/furniture/furniture-14.jpg',
      featured: false,
      leadTime: '15 - 20 business days'
    },
    {
      id: 'solid-hardwood-dining-table',
      name: 'Solid Wood Modern Dining Table & Bench Set',
      nameAm: 'የተሟላ የመመገቢያ ጠረጴዛና ቤንች',
      category: 'dining',
      categoryLabel: 'Dining Room',
      categoryLabelAm: 'የመመገቢያ ክፍል',
      dimensions: '220cm (L) x 95cm (W) x 75cm (H)',
      woodType: 'Solid Natural Wanza/Oak with Steel Spider Base',
      finish: 'Matte Protective Wood Stain & Natural Oil Topcoat',
      priceNote: 'Includes 8-seater table, matching bench, and 4 ergonomic chairs.',
      priceNoteAm: 'ጠረጴዛውን፣ ተስማሚ ቤንች እና ወንበሮችን ያጠቃልላል።',
      description: 'Handcrafted solid hardwood dining centerpiece with organic natural wood grains and modern matching dining benches.',
      descriptionAm: 'ከተፈጥሮ ጠንካራ እንጨት የተሰራ የመመገቢያ ጠረጴዛ ከውብ መቀመጫ ቤንች ጋር።',
      image: '/images/furniture/furniture-15.jpg',
      featured: true,
      leadTime: '14 - 21 business days'
    },
    {
      id: 'luxury-bar-cabinet-station',
      name: 'Custom Home Bar Cabinet & Glassware Showcase',
      nameAm: 'ዘመናዊ የመጠጥ እና የብርጭቆ ማሳያ ካቢኔት',
      category: 'dining',
      categoryLabel: 'Dining & Home Bar',
      categoryLabelAm: 'የመመገቢያና የመጠጥ ካቢኔት',
      dimensions: '160cm (W) x 220cm (H) x 45cm (D)',
      woodType: 'Dark Walnut & Fluted Glass Doors',
      finish: 'Mirrored Interior Backing & Warm Stemware Lighting',
      priceNote: 'Includes wine rack grids and hanging stemware racks.',
      priceNoteAm: 'የወይንና የብርጭቆ መስቀያዎችን ያጠቃልላል።',
      description: 'Refined entertainer bar cabinet with integrated wine grid racks, mirrored back panel, hanging stemware bronze tracks, and lockable storage.',
      descriptionAm: 'ለሳሎንና ለመመገቢያ ክፍል የሚሆን የሚያምር የመጠጥ ካቢኔት ከመስታወት በርና መብራት ጋር።',
      image: '/images/furniture/furniture-16.jpg',
      featured: false,
      leadTime: '10 - 15 business days'
    },
    {
      id: 'breakfast-counter-bar-stools',
      name: 'Quartz Breakfast Counter & Fluted Timber Stools',
      nameAm: 'የቁርስ ጠረጴዛ እና ከፍ ያሉ የእንጨት ወንበሮች',
      category: 'dining',
      categoryLabel: 'Dining & Kitchen Bar',
      categoryLabelAm: 'የቁርስ ባር ጠረጴዛ',
      dimensions: '180cm (L) x 60cm (W) x 90cm (H)',
      woodType: 'Solid Hardwood & Quartz Waterfall Edge',
      finish: 'Waterfall Edge Quartz & Matte Hardwood Stools',
      priceNote: 'Includes countertop extension and 3 matching barstools.',
      priceNoteAm: 'ጠረጴዛውንና 3 ከፍ ያሉ ወንበሮችን ያጠቃልላል።',
      description: 'Space-saving breakfast bar counter seamlessly adjoining open-plan kitchens, paired with handcrafted matching timber barstools.',
      descriptionAm: 'ለዘመናዊ ወጥ ቤት ተስማሚ የሆነ የቁርስ ባር ጠረጴዛ ከ3 ወንበሮች ጋር።',
      image: '/images/furniture/furniture-17.jpg',
      featured: false,
      leadTime: '8 - 12 business days'
    },
    {
      id: 'executive-curved-reception-desk',
      name: 'Bespoke Executive Curved Reception Desk',
      nameAm: 'ዘመናዊ የሪሴፕሽን እና የቢሮ ጠረጴዛ',
      category: 'office',
      categoryLabel: 'Executive Office & Reception',
      categoryLabelAm: 'ቢሮ እና ሪሴፕሽን',
      dimensions: '280cm (L) x 110cm (W) x 115cm (H)',
      woodType: 'Solid Hardwood & High Gloss Curved Fascia',
      finish: 'Warm LED Undermount Illumination & Polished Top',
      priceNote: 'Custom fabricated for commercial and corporate lobbies.',
      priceNoteAm: 'ለቢሮዎች እና ለንግድ ተቋማት የሚዘጋጅ።',
      description: 'Commanding executive reception workstation with built-in led illumination, wire grommets, internal shelving, and transaction tops.',
      descriptionAm: 'ለሆቴል፣ ስፓና ለኮርፖሬት ቢሮዎች የሚሆን ውብ የሪሴፕሽን ጠረጴዛ ከኤልኢዲ መብራት ጋር።',
      image: '/images/furniture/furniture-18.jpg',
      featured: true,
      leadTime: '12 - 18 business days'
    },
    {
      id: 'executive-conference-boardroom-table',
      name: 'Boardroom Conference Table & Media Workstations',
      nameAm: 'የስብሰባ አዳራሽ ጠረጴዛ እና የኮንፈረንስ እቃዎች',
      category: 'office',
      categoryLabel: 'Executive Office',
      categoryLabelAm: 'የቢሮና ስብሰባ አዳራሽ',
      dimensions: '380cm (L) x 140cm (W) x 76cm (H)',
      woodType: 'Solid Walnut Top with Heavy-Duty Powder Coated Steel Legs',
      finish: 'Scratch-Proof Matte Seal & Motorized Pop-up Connectivity Boxes',
      priceNote: 'Seats 10 to 14 participants with integrated HDMI/Power modules.',
      priceNoteAm: 'ከ10 እስከ 14 ሰዎችን የሚያስቀምጥ ከኤሌክትሪክና ኤችዲኤምአይ ገመድ ማገናኛ ጋር።',
      description: 'Prestigious conference table featuring integrated pop-up data boxes, cable spine conduits, and bevelled solid wood edge detailing.',
      descriptionAm: 'ለከፍተኛ የድርጅት ስብሰባዎች የሚሆን ባለ 14 ሰው ጠረጴዛ ከዘመናዊ የኬብል ማስተናገጃ ጋር።',
      image: '/images/furniture/furniture-19.jpg',
      featured: false,
      leadTime: '14 - 20 business days'
    },
    {
      id: 'managerial-l-shaped-desk',
      name: 'Managerial L-Shaped Executive Desk with Credenza',
      nameAm: 'የስራ አስኪያጅ ኤል-ቅርፅ ጠረጴዛ እና ካቢኔት',
      category: 'office',
      categoryLabel: 'Executive Office',
      categoryLabelAm: 'የስራ አስኪያጅ ቢሮ',
      dimensions: '220cm (L) x 180cm (Return) x 76cm (H)',
      woodType: 'Natural Teak & Matte Charcoal Lacquer',
      finish: 'Leather Desktop Inset & Lockable Soft-Close Drawers',
      priceNote: 'Includes return cabinet with CPU storage and document filing.',
      priceNoteAm: 'የሰነድ ማስቀመጫ ካቢኔት እና መሳቢያዎችን ያጠቃልላል።',
      description: 'Contemporary executive desk offering extensive workspace, integrated leather writing pad, lockable file drawers, and wire organizer passages.',
      descriptionAm: 'ለስራ አስኪያጅ የሚሆን ሰፊና ዘመናዊ ጠረጴዛ ከመቆለፊያ መሳቢያዎች ጋር።',
      image: '/images/furniture/furniture-20.jpg',
      featured: true,
      leadTime: '10 - 15 business days'
    }
  ];

  getFurnitureItems(): FurnitureItem[] {
    return this.furnitureItems;
  }

  getFeaturedFurniture(): FurnitureItem[] {
    return this.furnitureItems.filter(f => f.featured);
  }

  getFurnitureById(id: string): FurnitureItem | undefined {
    return this.furnitureItems.find(f => f.id === id);
  }

  getFurnitureByCategory(category: string): FurnitureItem[] {
    if (category === 'all') return this.furnitureItems;
    return this.furnitureItems.filter(f => f.category === category);
  }
}
